INSERT INTO public.app_disease (name) VALUES
('Acute Coronary Syndrome (एक्युट कोरोनरी सिन्ड्रोम)'),
('Acute Respiratory Infection (ARI) (सानो श्वासप्रश्वासको संक्रमण)'),
('Alzheimer''s Disease (अल्जाइमर रोग)'),
('Anemia (रक्तअल्पता)'),
('Anxiety (चिन्ता)'),
('Aortic Aneurysm (महाधमनी एन्युरिज्म)'),
('Arrhythmia (अनियमित हृदयघडी)'),
('Asthma (दम)'),
('Back Pain (कम्मर दुखाइ)'),
('Benign Prostatic Hyperplasia (BPH) (प्रोस्टेट बढी)'),
('Bipolar Disorder (बाइपोलर डिसअर्डर)'),
('Brain Tumors (मस्तिष्कको ट्युमर)'),
('Breast Cancer (स्तन क्यान्सर)'),
('Bronchiectasis (ब्रोन्किएक्टेसिस)'),
('Bronchiolitis (ब्रोन्कियोलाइटिस)'),
('Burns (पोल्ने)'),
('Cancer (क्यान्सर)'),
('Cardiomyopathy (हृदयमांसपेशीको रोग)'),
('Cataracts (मोतियाबिंद)'),
('Cervical Cancer (गर्भाशयको क्यान्सर)'),
('Childhood Cancers (बाल्यकालीन क्यान्सर)'),
('Cholera (हैजा)'),
('Chronic Kidney Disease (CKD) (क्रोनिक किडनी रोग)'),
('Chronic Obstructive Pulmonary Disease (COPD) (क्रोनिक अब्स्ट्रक्टिभ पल्मोनरी डिजिज)'),
('Chronic Pancreatitis (क्रोनिक प्यान्क्रियाटाइटिस)'),
('Cirrhosis (कलेजो सिरोसिस)'),
('Colorectal Cancer (आन्द्रा र मलाशयको क्यान्सर)'),
('Community-Acquired Pneumonia (सामुदायिक निमोनिया)'),
('Compartment Syndrome (कम्पार्टमेन्ट सिन्ड्रोम)'),
('Congenital Heart Defects (जन्मजात हृदय दोष)'),
('Conjunctivitis (आँखा आउने)'),
('Corneal Ulcers & Scars (कर्नियल अल्सर)'),
('Coronary Artery Disease (करोनरी धमनी रोग)'),
('Crush Injuries (क्रश चोट)'),
('Deep Vein Thrombosis (DVT) (गहिरो शिरा थ्रोम्बोसिस)'),
('Dementia (डिमेन्सिया)'),
('Dengue (डेंगु)'),
('Depression (डिप्रेसन)'),
('Diabetes/Type 2 Diabetes (मधुमेह)'),
('Diabetic Nephropathy (मधुमेह नेफ्रोपैथी)'),
('Diabetic Retinopathy (मधुमेह रेटिनोपैथी)'),
('Diarrhea (पखाला)'),
('Ear infections (कानको संक्रमण)'),
('Ectopic Pregnancy (एक्टोपिक प्रेगनेन्सी)'),
('End-Stage Renal Disease (ESRD) (किडनी फेल)'),
('Endometriosis (एन्डोमेट्रियोसिस)'),
('Epilepsy (मिर्गौला)'),
('Fibroids (गर्भाशयमा ढिकी)'),
('Food-borne infections (खानाबाट हुने संक्रमण)'),
('Frostbite (हिउँदो चोट)'),
('Fungal Infections (कवक संक्रमण)'),
('Gallstones (पित्तघट्टा)'),
('Gastroesophageal Reflux Disease (GERD) (ग्यास्ट्रोइसोफेगल रिफ्लक्स रोग)'),
('Gestational Diabetes (गर्भावस्थाको मधुमेह)'),
('Glaucoma (काला पानी)'),
('Gout (गाउट)'),
('Head & Neck Cancer (टाउको र घाँटीको क्यान्सर)'),
('Head Injuries (टाउकोको चोट)'),
('Headaches (टाउको दुखाइ)'),
('Heart Disease (हृदय रोग)'),
('Heart Failure (हृदय फेल)'),
('Hepatitis (हेपाटाइटिस)'),
('High Altitude Sickness (अग्लो स्थानको रोग)'),
('High-Risk Pregnancies (उच्च जोखिम गर्भावस्था)'),
('HIV/AIDS (एचआईभी/एड्स)'),
('Hypertension/High Blood Pressure (उच्च रक्तचाप)'),
('Inflammatory Bowel Disease (IBD) (इन्फ्लामेटरी बोवेल डिजिज)'),
('Iron Deficiency Anemia (फलामको कमी)'),
('Irritable Bowel Syndrome (IBS) (इर्रिटेबल बोवेल सिन्ड्रोम)'),
('Ischemic Heart Disease (इस्केमिक हृदय रोग)'),
('Jaundice (पियाहा)'),
('Kala-azar (काला आजार)'),
('Kwashiorkor (क्वासियोर्कर)'),
('Leptospirosis (लेप्टोस्पायरोसिस)'),
('Leukemia (ब्लड क्यान्सर)'),
('Liver Abscess (कलेजोको फोका)'),
('Liver Cirrhosis (कलेजो सिरोसिस)'),
('Lumbar Spondylosis (कम्मरको अस्थिसंधिशोथ)'),
('Lung Cancer (फोक्सोको क्यान्सर)'),
('Lymphoma (लिम्फोमा)'),
('Macular Degeneration (म्याकुलर डिजेनरेशन)'),
('Malaria (मलेरिया)'),
('Malnutrition (कुपोषण)'),
('Marasmus (मरास्मस)'),
('Meningitis (मस्तिष्कको आवरण सुन्निने रोग)'),
('Migraine (आधाशीशी)'),
('Multiple Sclerosis (मल्टिपल स्केलेरोसिस)'),
('Neonatal Jaundice (नयाँजातको पियाहा)'),
('Neonatal Sepsis (नयाँजातको सेप्सिस)'),
('Neuropathies (नसाका रोग)'),
('Orbital Tumors (आँखाको गर्भको ट्युमर)'),
('Osteoarthritis (अस्थिसंधिशोथ)'),
('Osteoporosis (हड्डीको घनत्व घट्ने)'),
('Pancreatitis (प्यान्क्रियाटाइटिस)'),
('Parkinson''s Disease (पार्किन्सन्स रोग)'),
('Pediatric Blindness (बाल्यकालीन अन्धापन)'),
('Peptic Ulcer Disease (पेप्टिक अल्सर)'),
('Peripheral Vascular Disease (पेरिफेरल भास्कुलर रोग)'),
('Pituitary Disorders (पिट्युटरी ग्रन्थिको रोग)'),
('Pleural Effusion (फोक्सोमा पानी जम्ने)'),
('Pneumonia (निमोनिया)'),
('Polycystic Kidney Disease (पोलिसिस्टिक किडनी रोग)'),
('Polycystic Ovary Syndrome (PCOS) (पोलिसिस्टिक ओभरी सिन्ड्रोम)'),
('Polytrauma (बहु-चोट)'),
('Post-Traumatic Stress Disorder (PTSD) (पोस्ट-ट्राउमाटिक स्ट्रेस डिसअर्डर)'),
('Postpartum Complications (प्रसूतपछिका जटिलताहरू)'),
('Postpartum Depression (प्रसूतपछि डिप्रेसन)'),
('Preeclampsia (प्री-एक्लेम्पसिया)'),
('Prematurity (अकाल जन्म)'),
('Psychosis (साइकोसिस)'),
('Refractive Errors (दृष्टि दोष)'),
('Renal Colic (गुराँउको दुखाइ)'),
('Retinal Detachment (रेटिना अलगिने)'),
('Retinoblastoma (रेटिनोब्लास्टोमा)'),
('Rheumatic Heart Disease (रुमेटिक हृदय रोग)'),
('Rheumatoid Arthritis (रुमेटोइड आर्थराइटिस)'),
('Rotavirus (रोटाभाइरस)'),
('Scabies (खजुरी)'),
('Schizophrenia (स्किजोफ्रेनिया)'),
('Scrub Typhus (स्क्रब टाइफस)'),
('Sepsis (सेप्सिस)'),
('Sexually Transmitted Infections (STIs) (यौनसंचारित संक्रमण)'),
('Sinusitis (साइनसाइटिस)'),
('Skin Allergies (छालाको एलर्जी)'),
('Skin Infections (छालाको संक्रमण)'),
('Skin Rashes (छालामा ददुरा)'),
('Snake Bites (सर्पदंश)'),
('Soft Tissue Injuries (नरम ऊतकको चोट)'),
('Solid Tumors (ठोस ट्युमर)'),
('Spinal Cord Disorders (रीढको हड्डीका रोग)'),
('Spine Disorders/Spinal Stenosis (रीढको हड्डीको रोग)'),
('Sports Injuries (खेलकुद चोटपटक)'),
('Stomach Cancer (पेटको क्यान्सर)'),
('Stress-related issues (तनावसम्बन्धी समस्या)'),
('Strabismus/Squint (भेगो आँखा)'),
('Stroke (स्ट्रोक)'),
('Systemic Lupus Erythematosus (SLE) (लुपस)'),
('Thalassemia (थैलेसिमिया)'),
('Thyroid Disorders (थाइरोइडको रोग)'),
('Tonsillitis (टन्सिलाइटिस)'),
('Traumatic Eye Injuries (आँखाको चोटपटक)'),
('Traumatic Shock (चोटपटकबाट हुने सक)'),
('Trigeminal Neuralgia (ट्राइजेमिनल न्युराल्जिया)'),
('Tuberculosis (TB) (क्षयरोग)'),
('Typhoid (टाइफाइड)'),
('Underweight children (कम तौलका बच्चाहरू)'),
('Urinary Tract Infection (UTI) (मूत्रमार्ग संक्रमण)'),
('Urolithiasis/Kidney Stones (गुराँसको ढुङ्गा)'),
('Uveitis (युभेइटिस)'),
('Valvular Heart Disease (हृदयको भाल्व रोग)'),
('Vertigo (घुम्टो)'),
('Viral Fevers (भाइरल ज्वरो)'),
('Vitamin deficiencies (भिटामिनको कमी)'),
('Wilms'' Tumor (विल्म्स ट्युमर)'),
('Worms Infestation (कृमि संक्रमण)');