INSERT INTO public.app_surg (name) VALUES
	 ('Abdominal Hysterectomy (पेटबाट गर्भाशय निकाल्ने)'),
	 ('Abdominoperineal Resection (एब्डोमिनोपेरिनियल रिसेक्सन)'),
	 ('ACL Reconstruction (ACL रिकन्स्ट्रक्सन)'),
	 ('Appendectomy (अपेन्डिक्सको शल्यचिकित्सा)'),
	 ('Arthroscopy (आर्थ्रोस्कोपी)'),
	 ('AV Fistula Surgery (एभी फिस्टुला सर्जरी)'),
	 ('Beating Heart CABG (बिटिङ हार्ट बाइपास)'),
	 ('Biopsy (बायोप्सी)'),
	 ('Burr Hole Surgery (बर होल सर्जरी)'),
	 ('CABG - Coronary Artery Bypass Grafting (बाइपास सर्जरी)'),
	 ('Carotid Endarterectomy (क्यारटिड एन्डार्टेरेक्टोमी)'),
	 ('Carpal Tunnel Release (कार्पल टनेल रिलिज)'),
	 ('Cataract Surgery (मोतियाबिंदको शल्यचिकित्सा)'),
	 ('Cervical Cerclage (सर्भिकल सर्क्लेज)'),
	 ('Cesarean Section - C-Section (सिजेरियन सेक्सन)'),
	 ('Chest Tube Insertion (छातीमा ट्युब राख्ने)'),
	 ('Cholecystectomy - Gallbladder Removal (पित्तको थैली निकाल्ने)'),
	 ('Circumcision (खतना)'),
	 ('Cleft Lip/Palate Repair (क्लेफ्ट लिप/प्यालट मर्मत)'),
	 ('Closed Reductions (बन्द रिडक्सन)'),
	 ('Colectomy (कोलेक्टोमी)'),
	 ('Colostomy (कोलोस्टोमी)'),
	 ('Corneal Transplant - Keratoplasty (कर्नियल प्रत्यारोपण)'),
	 ('Coronary Angioplasty & Stenting - PCI (कोरोनरी एन्जियोप्लास्टी र स्टेन्टिंग)'),
	 ('Craniotomy (क्रेनियोटोमी)'),
	 ('Cystectomy - Bladder Removal (मूत्राशय निकाल्ने)'),
	 ('D&C - Dilation and Curettage (D&C)'),
	 ('Debridement (डेब्रिडमेन्ट)'),
	 ('DCR - Dacryocystorhinostomy (DCR)'),
	 ('Discectomy (डिस्केक्टोमी)'),
	 ('Dynamic Hip Screw - DHS Fixation (DHS फिक्सेसन)'),
	 ('Ectopic Pregnancy Surgery (एक्टोपिक प्रेगनेन्सीको शल्यचिकित्सा)'),
	 ('Enucleation/Evisceration - Eye Removal (आँखा निकाल्ने)'),
	 ('External Fixation (एक्सटर्नल फिक्सेसन)'),
	 ('Fasciotomy (फ्यासियोटोमी)'),
	 ('Functional Endoscopic Sinus Surgery - FESS (FESS)'),
	 ('Fundoplication for GERD (GERD को लागि फन्डोप्लिकेसन)'),
	 ('Gastrectomy - Stomach Removal (पेट निकाल्ने)'),
	 ('Hemiarthroplasty (हेमियार्थ्रोप्लास्टी)'),
	 ('Hemicolectomy (हेमिकोलेक्टोमी)'),
	 ('Hemodialysis Access Surgery (हेमोडायलिसिस एक्सेस सर्जरी)'),
	 ('Hemorrhoidectomy - Hemorrhoids Surgery (बवासीरको शल्यचिकित्सा)'),
	 ('Hernia Repair - Hernioplasty/Herniorrhaphy (हर्नियाको मर्मत)'),
	 ('Hydrocelectomy (हाइड्रोसिलको शल्यचिकित्सा)'),
	 ('Hysterectomy - Uterus Removal (गर्भाशय निकाल्ने)'),
	 ('Hypospadias Repair (हाइपोस्पेडियास मर्मत)'),
	 ('ICD Implantation (ICD इम्प्लान्टेसन)'),
	 ('Ilizarov Fixation (इलिजारोव फिक्सेसन)'),
	 ('Incision & Drainage - I&D (चिर्ने र निकास्ने)'),
	 ('Intestinal Obstruction Surgery (आन्द्रा बन्द हुनेको शल्यचिकित्सा)'),
	 ('Intussusception Reduction (इन्टुससेप्सन रिडक्सन)'),
	 ('Kidney Transplantation (गुराँउ प्रत्यारोपण)'),
	 ('Laminectomy (लामिनेक्टोमी)'),
	 ('Laparoscopic Cholecystectomy (ल्यापरोस्कोपिक पित्तको थैली निकाल्ने)'),
	 ('Laparoscopic Gynecological Surgeries (ल्यापरोस्कोपिक स्त्रीरोग शल्यचिकित्सा)'),
	 ('Laparoscopic Hysterectomy (ल्यापरोस्कोपिक हिस्टेरेक्टोमी)'),
	 ('Laparoscopic Ovarian Cystectomy (ल्यापरोस्कोपिक ओभेरियन सिस्टेक्टोमी)'),
	 ('Laparoscopic Sterilization (ल्यापरोस्कोपिक बन्ध्याकरण)'),
	 ('Laparoscopic Tubal Ligation (ल्यापरोस्कोपिक ट्युबल लाइगेसन)'),
	 ('Laparotomy (ल्यापरोटोमी)'),
	 ('Limb Amputation (for Sarcoma) (सरकोमाको लागि हात वा खुट्टा काट्ने)'),
	 ('Liver Transplantation (कलेजो प्रत्यारोपण)'),
	 ('Mastectomy - Breast Removal (स्तन निकाल्ने)'),
	 ('Mastoidectomy (मास्टोइडेक्टोमी)'),
	 ('Microdiscectomy (माइक्रोडिस्केक्टोमी)'),
	 ('Microvascular Decompression (माइक्रोभास्कुलर डिकम्प्रेसन)'),
	 ('Minimally Invasive Cardiac Surgery (मिनिमली इन्भेसिभ कार्डियाक सर्जरी)'),
	 ('Wound Suture (घाउ टाँस्ने)'),
	 ('Modified Radical Mastectomy - MRM (मोडिफाइड र्याडिकल मास्टेक्टोमी)'),
	 ('Myomectomy - Fibroid Removal (गर्भाशयमा ढिकी निकाल्ने)'),
	 ('Nephrectomy - Kidney Removal (गुराँउ निकाल्ने)'),
	 ('Nephrolithotomy (नेफ्रोलिथोटोमी)'),
	 ('Nissen Fundoplication (निसन फन्डोप्लिकेसन)'),
	 ('Oculoplasty (अकुलोप्लास्टी)'),
	 ('Open Reduction and Internal Fixation - ORIF of Fractures (फ्र्याक्चरको प्लेटिंग)'),
	 ('Orchiopexy (ओर्कियोपेक्सी)'),
	 ('Ovarian Cystectomy - Ovary Cyst Removal (अण्डाशयको सिस्ट निकाल्ने)'),
	 ('Pacemaker Implantation (पेसमेकर इम्प्लान्टेसन)'),
	 ('Palliative Surgeries (प्यालिएटिभ सर्जरी)'),
	 ('PDA Ligation (PDA लाइगेसन)'),
	 ('Perforation Repair (पेरफोरेसनको मर्मत)'),
	 ('Peripheral Vascular Bypass (पेरिफेरल भास्कुलर बाइपास)'),
	 ('Peritoneal Dialysis Catheter Insertion (पेरिटोनियल डायलिसिस क्याथेटर राख्ने)'),
	 ('Phacoemulsification (फेकोइमल्सिफिकेसन)'),
	 ('Pituitary Surgery (पिट्युटरी ग्रन्थिको शल्यचिकित्सा)'),
	 ('Polytrauma Management (पोलिट्राउमा व्यवस्थापन)'),
	 ('Proximal Femoral Nail - PFN Fixation (PFN फिक्सेसन)'),
	 ('Pterygium Excision (टेरिजियम एक्सिजन)'),
	 ('Pyloromyotomy (पाइलोरोमायोटोमी)'),
	 ('Pyelolithotomy (पाइलोलिथोटोमी)'),
	 ('Pyeloplasty (पाइलोप्लास्टी)'),
	 ('Radical Hysterectomy (र्याडिकल हिस्टेरेक्टोमी)'),
	 ('Radical Neck Dissection (र्याडिकल नेक डिसेक्सन)'),
	 ('Radical Nephrectomy (र्याडिकल नेफ्रेक्टोमी)'),
	 ('Radical Prostatectomy (र्याडिकल प्रोस्टेटेक्टोमी)'),
	 ('Reconstructive Surgeries (पुनर्निर्माण शल्यचिकित्सा)'),
	 ('Repair of Congenital Diaphragmatic Hernia (जन्मजात डायाफ्रामेटिक हर्निया मर्मत)'),
	 ('Repair of Genital Fistulas (जननांग फिस्टुला मर्मत)'),
	 ('Repair of Perineal Tears (पेरिनियल फाटा मर्मत)'),
	 ('Repair of Uterine Rupture (गर्भाशय फुट्नेको मर्मत)'),
	 ('Retinal Detachment Repair (रेटिना अलगिनेको मर्मत)'),
	 ('Rhinoplasty (राइनोप्लास्टी)'),
	 ('Septoplasty (सेप्टोप्लास्टी)'),
	 ('Skin Grafting (छाला प्रत्यारोपण)'),
	 ('Spinal Decompression & Fusion (स्पाइनल डिकम्प्रेसन र फ्युजन)'),
	 ('Spinal Instrumentation (स्पाइनल इन्स्ट्रुमेन्टेसन)'),
	 ('Splenectomy - Spleen Removal (प्लीहा निकाल्ने)'),
	 ('Squint Surgery - Surgery for Strabismus (भेगो आँखाको शल्यचिक्सा)'),
	 ('Stapedectomy (स्टेपेडेक्टोमी)'),
	 ('Surgery for Aortic Dissection (महाधमनी डिसेक्सनको शल्यचिकित्सा)'),
	 ('Surgery for Congenital Defects - ASD/VSD/TOF Repair (जन्मजात हृदय दोषको शल्यचिकित्सा)'),
	 ('Surgery for Trigeminal Neuralgia (ट्राइजेमिनल न्युराल्जियाको शल्यचिकित्सा)'),
	 ('Tendon Repair (टेन्डन मर्मत)'),
	 ('Thoracotomy (थोराकोटोमी)'),
	 ('Thyroidectomy - Thyroid Removal (थाइरोइड निकाल्ने)'),
	 ('TLH - Total Laparoscopic Hysterectomy (TLH)'),
	 ('Tonsillectomy - Tonsils Removal (टन्सिल निकाल्ने)'),
	 ('Total Hip Replacement (कम्मरको जोर्नी बदल्ने)'),
	 ('Total Hip/Knee Arthroplasty (हिप/नी आर्थ्रोप्लास्टी)'),
	 ('Total Hip/Knee Replacement (हिप/नी रिप्लेसमेन्ट)'),
	 ('Total Joint Arthroplasty (जोइन्ट आर्थ्रोप्लास्टी)'),
	 ('Total Joint Replacement (जोइन्ट रिप्लेसमेन्ट)'),
	 ('Total Knee Replacement (घुँडाको जोर्नी बदल्ने)'),
	 ('Trabeculectomy - Glaucoma Surgery (ट्राबेकुलेक्टोमी)'),
	 ('Transurethral Resection of Bladder Tumor - TURBT (TURBT)'),
	 ('Transurethral Resection of Prostate - TURP (TURP)'),
	 ('Tubal Ligation - Female Sterilization (ट्युबल लाइगेसन)'),
	 ('Tumor Debulking (ट्युमर डिबल्किंग)'),
	 ('Tympanoplasty (टिम्पानोप्लास्टी)'),
	 ('Vaginal Hysterectomy (योनिबाट गर्भाशय निकाल्ने)'),
	 ('Valve Repair/Replacement (हृदय भाल्व मर्मत/बदल्ने)'),
	 ('Vascular Repair (भास्कुलर मर्मत)'),
	 ('Vasectomy - Vas Ligation (नसबन्धी)'),
	 ('Vitrectomy (भिट्रेक्टोमी)'),
	 ('VP Shunt (VP शन्ट)');
